#!/bin/bash

echo "Starting on `hostname` at `date`" >> log

./rcsj >> log 2>&1 <<EOF
X # Visualization

: Ic = 1
: C = 1.2337    # Q^2 factor = beta in dimenstionless units.
: C0 = 0.01     # Q^2 / lambda^2.  velocity is lambda/Q = 10 junctions/time unit
: R = 1
: Rqp = 1000
: Rterm = 200
: Rshunt = 0.125
# : Cterm = 0    # 0 means Cterm=C0.
: Cterm = 2000   # What is a good number?
#: Lterm = 10     # Bias tee L
#: Ramp = 0.125   # 50 Ohm seems too much???   # Ramp amplifier resistance 50 Ohm
#: Camp = 4000    # Low pass filter. I think 4000 ~ 1 pF.
: T = 0.005 # in units of EJ = L Ic^2 = (Delta/2)(R_Q/R) = 0.88 Tc * (R_Q/R).
: Vgap = 1      # Gap voltage. Put equal 0 if you want ohmic behavior.
: circuit_layout = ordinary
: init_voltages = false
: dt = 0.01 # Time step. Default is 0.02.
# : dt = sqrt(LC)* 0.02 # May also be set automatically in this way.
: dt = 0.1

# Run simulation

# Note bias current approximately Ib = U/R = U / 200 in the superconducting state.
# Total sum gap voltage is Lx * Vg = 400 * 1 = 400

#   Lx      number  sweeps  equil   Umin    Ustep   Umax

u   401     1000000  10      1000000     0     10      100
u   401     1000000  10      1000000   100      5      150
u   401     1000000  10      1000000   155      1      170
u   401     1000000  10      1000000   171    0.5      200
u   401     1000000  10      1000000   201      1      450
u   401     1000000  10      1000000   455      5      500
u   401     1000000  10      1000000   510     10     1000
u   401     1000000  10      1000000  1100    100     2000

!mkdir -p up
!mv PS_* up

# Reverse sweep:

u   401     1000000  10      1000000  1000   -100      400
u   401     1000000  10      1000000   400    -10      190
u   401     1000000  10      1000000   185     -5      100
u   401     1000000  10      1000000    90    -10      0
Q
EOF

echo "Stopping on `hostname` at `date`" >> log
